locallibrary/catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("books/", views.BookListView.as_view(), name="books"),
    path("books/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path(
        "books/<uuid:pk>/renew", views.renew_book_librarian, name="renew-book-librarian"
    ),
    path("book/<uuid:pk>/borrow/", views.borrow_book, name="borrow-book"),
    path("mybooks/", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
] 

locallibrary/catalog/models.py
from django.db import models
from datetime import date
from django.urls import reverse
from django.utils.translation import gettext
from django.contrib.auth.models import User
import uuid
from .constants import (
    MAX_LENGTH_IMPRINT,
    MAX_LENGTH_ISBN,
    MAX_LENGTH_NAME,
    MAX_LENGTH_SUMMARY,
    MAX_LENGTH_TITLE,
    MAX_LENGTH_STATUS,
    LOAN_STATUS,
)

# Create your models here.

class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=MAX_LENGTH_TITLE, 
        help_text=gettext('Enter a book genre (e.g.Science Fiction)'),
    )
    
    def __str__(self):
        """String for representing the Model object."""
        return self.name
    
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=MAX_LENGTH_TITLE)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(
        max_length=MAX_LENGTH_SUMMARY, 
        help_text=gettext('Enter a brief description of the book'),
    )

    isbn = models.CharField(
        'ISBN', 
        max_length=MAX_LENGTH_ISBN, 
        unique=True,
        help_text=gettext(
            '13 Character <ahref="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
        ),
    )
    
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    
    def __str__(self):
        """String for representing the Model object."""
        return self.title
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])
    
    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = "Genre"

class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        help_text=gettext(
            "Unique ID for this particular book across whole library"),
    )
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(
        max_length=MAX_LENGTH_STATUS,
        choices=[
            (tag.value, tag.name.replace("_", " ").title()) for tag in LOAN_STATUS
        ],
        blank=True,
        default=LOAN_STATUS.MAINTENANCE.value,
        help_text=gettext('Book availability'),
    )
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)
        
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back

    
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=MAX_LENGTH_NAME)
    last_name = models.CharField(max_length=MAX_LENGTH_NAME)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    
    class Meta:
        ordering = ['last_name', 'first_name']
        
    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])
    
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

locallibrary/catalog/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .constants import NUM_OF_WEEKS
from catalog.models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text=_("Enter a date between now and 4 weeks" "(default 3).")
    )

    def clean_renewal_date(self):
        data = self.cleaned_data["renewal_date"]
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        if data > datetime.date.today() + datetime.timedelta(weeks=NUM_OF_WEEKS):
            raise ValidationError(
                _(f"Invalid date - renewal more than {NUM_OF_WEEKS} weeks")
            )
        return data


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data["due_back"]
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))
        if data > datetime.date.today() + datetime.timedelta(weeks=NUM_OF_WEEKS):
            raise ValidationError(
                _(f"Invalid date - renewal more than {NUM_OF_WEEKS} weeks")
            )
        return data

    class Meta:
        model = BookInstance
        fields = ["due_back"]
        labels = {"due_back": _("Renewal date")}
        help_texts = {
            "due_back": _(
                f"Enter a date between now and {NUM_OF_WEEKS} weeks (default 3). "
            )
        }
        

locallibrary/catalog/views.py
import datetime
from urllib import request
from django.shortcuts import render
from django.views import generic, View
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.http import require_POST
from .models import Book, Author, BookInstance, Genre
from .constants import (
    LOAN_STATUS,
    NUM_BOOK_VIEW,
    NUM_VISITS,
    NUM_OF_WEEKS_DEFAULT,
    INITIAL_DATE_OF_DEATH,
)
from .forms import RenewBookForm

# Create your views here.

def index(request):
    """View function for home page of site."""
    
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status__exact=LOAN_STATUS.AVAILABLE.value
    ).count()
    
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', NUM_VISITS)
    request.session['num_visits'] = num_visits + NUM_VISITS
    
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
    }
    
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = NUM_BOOK_VIEW
    context_object_name = "book_list"
    template_name = "catalog/book_list.html"
    queryset = Book.objects.all().order_by("title")


class BookDetailView(generic.DetailView):
    """Generic class-based view for a book detail page."""

    model = Book

    def get_context_data(self, **kwargs):
        """Add additional context data to the view."""
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context["LOAN_STATUS"] = LOAN_STATUS
        context["book_instances"] = self.object.bookinstance_set.all()
        return context

    def book_detail_view(self, primary_key):
        """View function for displaying a book detail page."""
        book = get_object_or_404(Book, pk=primary_key)

        return render(request, "catalog/book_detail.html", context={"book": book})


class LoanedBooksByUserListView(generic.ListView):
    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = NUM_BOOK_VIEW

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact=LOAN_STATUS.ON_LOAN.value)
            .order_by("due_back")
        )


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == "POST":
        form = RenewBookForm(request.POST)
    if form.is_valid():
        book_instance.due_back = form.cleaned_data["renewal_date"]
        book_instance.save()
        return HttpResponseRedirect(reverse("all-borrowed"))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(
            weeks=NUM_OF_WEEKS_DEFAULT
        )
        form = RenewBookForm(initial={"renewal_date": proposed_renewal_date})

    context = {"form": form, "book_instance": book_instance}

    return render(request, "catalog/book_renew_librarian.html", context)


@login_required
@require_POST
def borrow_book(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if book_instance.status != LOAN_STATUS.AVAILABLE.value:
        return redirect("book-detail", pk=book_instance.book.pk)

    book_instance.status = LOAN_STATUS.ON_LOAN.value
    book_instance.borrower = request.user
    book_instance.due_back = datetime.date.today() + datetime.timedelta(
        weeks=NUM_OF_WEEKS_DEFAULT
    )
    book_instance.save()

    return redirect("book-detail", pk=book_instance.book.pk)


class AuthorCreate(CreateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": INITIAL_DATE_OF_DEATH}


class AuthorUpdate(UpdateView):
    model = Author
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy("authors")

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}
{% load i18n %}
{% block content %}
<h1>{% trans "Delete Author" %}</h1>
<p>{% trans "Are you sure you want to delete the author: " %} {{ author }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Title" %}: {{ book.title }}</h1>


    <p><strong>{% trans "Author" %}:</strong> <a href="">{{ book.author }}</a></p>
    <p><strong>{% trans "Summary" %}:</strong> {{ book.summary }}</p>
    <p><strong>{% trans "ISBN" %}:</strong> {{ book.isbn }}</p>
    <p><strong>{% trans "Language" %}:</strong> {{ book.language }}</p>
    <p><strong>{% trans "Genre" %}:</strong> {{ book.genre.all|join:", " }}</p>

    <div class="book-detail-copies">
        <h4>{% trans "Copies" %}</h4>
        {% for copy in book_instances %}
            <hr>
            <p class="
                {% if copy.status == LOAN_STATUS.AVAILABLE.value %}
                    text-success
                {% elif copy.status == LOAN_STATUS.MAINTENANCE.value %}
                    text-danger
                {% else %}
                    text-warning
                {% endif %}
            ">
            {{ copy.get_status_display }}
            </p>
            {% if copy.status != LOAN_STATUS.AVAILABLE.value %}
                <p><strong>{% trans "Due to be returned" %}:</strong> {{ copy.due_back }}</p>
            {% endif %}
                <p><strong>{% trans "Imprint" %}:</strong> {{ copy.imprint }}</p>
                <p class="text-muted"><strong>{% trans "Id" %}:</strong> {{ copy.id }}</p>

            <!-- Action buttons -->
            {% if copy.status == LOAN_STATUS.AVAILABLE.value %}
                <form method="post" action="{% url 'borrow-book' copy.pk %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">{% trans "Borrow this copy" %}</button>
                </form>
            {% elif copy.status == LOAN_STATUS.ON_LOAN.value and copy.borrower == user %}
                <a class="btn btn-warning mt-2" href="{% url 'renew-book' copy.pk %}">{% trans "Renew this copy" %}</a>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Book List" %}</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books in the library" %}.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
<h1>{% trans "Renew: " %}{{ book_instance.book.title }}</h1>
<p>{% trans "Borrower: " %} {{ book_instance.borrower }}</p>
<p {% if book_instance.is_overdue %} class="text-danger"{% endif %}>
    {% trans "Due date: " %} {{ book_instance.due_back }}
</p>

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Borrowed books" %}</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
                    ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}